// REFERENSI UI/src/pages/Dashboard.tsx
import { FileText, TrendingUp, TrendingDown, AlertCircle, Clock, CheckCircle, MinusCircle, ArrowRight } from "lucide-react";
import { XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar } from "recharts";
import { PENGELUARAN, formatRupiah, formatDate, getPaymentSummary, type Invoice, type Pembayaran, type Pemasukan, type Role } from "@/data/mock";
import { StatusPembayaranBadge } from "@/components/Badge";
import type { Page } from "@/App";

const chartData = [
  { name: "Mar", pemasukan: 4200000, pengeluaran: 1800000 },
  { name: "Apr", pemasukan: 5800000, pengeluaran: 2200000 },
  { name: "Mei", pemasukan: 3900000, pengeluaran: 1500000 },
  { name: "Jun", pemasukan: 7200000, pengeluaran: 3100000 },
  { name: "Jul", pemasukan: 6100000, pengeluaran: 2400000 },
  { name: "Agu", pemasukan: 8350000, pengeluaran: 3300000 },
];

const formatRpShort = (v: number) => {
  if (v >= 1000000) return `Rp ${(v / 1000000).toFixed(1)}jt`;
  if (v >= 1000) return `Rp ${(v / 1000).toFixed(0)}rb`;
  return `Rp ${v}`;
};

interface Props {
  role: Role;
  onNavigate: (page: Page, id?: string) => void;
  invoices: Invoice[];
  payments: Pembayaran[];
  pemasukan: Pemasukan[];
}

export default function Dashboard({ onNavigate, invoices, payments, pemasukan }: Props) {
  const invoiceRows = invoices.map(invoice => ({ ...invoice, ...getPaymentSummary(invoice, payments) }));
  const totalInvoice = invoices.filter(invoice => invoice.statusDokumen !== "dibatalkan").length;
  const sisaTagihan = invoiceRows
    .filter(invoice => invoice.statusDokumen === "diterbitkan")
    .reduce((sum, invoice) => sum + invoice.sisaTagihan, 0);
  const totalPemasukan = pemasukan.reduce((sum, item) => sum + item.nominal, 0);
  const totalPengeluaran = PENGELUARAN.reduce((s, p) => s + p.nominal, 0);

  const statusCounts = {
    belum_dibayar: invoiceRows.filter(invoice => invoice.statusPembayaran === "belum_dibayar" && invoice.statusDokumen !== "dibatalkan").length,
    dibayar_sebagian: invoiceRows.filter(invoice => invoice.statusPembayaran === "dibayar_sebagian" && invoice.statusDokumen !== "dibatalkan").length,
    lunas: invoiceRows.filter(invoice => invoice.statusPembayaran === "lunas" && invoice.statusDokumen !== "dibatalkan").length,
    jatuh_tempo: invoiceRows.filter(invoice => invoice.statusPembayaran === "jatuh_tempo" && invoice.statusDokumen !== "dibatalkan").length,
  };

  const recentInvoices = invoiceRows
    .slice()
    .sort((a, b) => b.tanggalInvoice.localeCompare(a.tanggalInvoice))
    .slice(0, 5);

  return (
    <div className="p-6 space-y-4">
      {/* Page header */}
      <div className="flex items-center justify-between pb-1">
        <div>
          <h1 className="text-[18px] font-semibold text-[#172033] leading-snug">Dashboard</h1>
          <p className="text-[13px] text-[#9CA3AF] mt-0.5">Ringkasan keuangan dan aktivitas terkini</p>
        </div>
        <select className="h-8 pl-3 pr-8 text-[13px] border border-[#E2E6EC] rounded-md text-[#667085] bg-white focus:outline-none focus:border-[#173B6C]"
          style={{ backgroundImage: "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='10' viewBox='0 0 24 24' fill='none' stroke='%239CA3AF' stroke-width='2'%3E%3Cpath d='M6 9l6 6 6-6'/%3E%3C/svg%3E\")", backgroundRepeat: "no-repeat", backgroundPosition: "right 8px center", appearance: "none" }}>
          <option>Bulan Ini</option>
          <option>3 Bulan Terakhir</option>
          <option>Tahun Ini</option>
        </select>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-4 gap-3.5">
        <SummaryCard
          label="Total Invoice"
          value={totalInvoice.toString()}
          sub="invoice aktif"
          icon={<FileText size={15} />}
          onClick={() => onNavigate("invoice")}
          accent="#173B6C"
        />
        <SummaryCard
          label="Sisa Tagihan"
          value={formatRupiah(sisaTagihan)}
          sub="belum terlunasi"
          icon={<AlertCircle size={15} />}
          onClick={() => onNavigate("billing")}
          accent="#D97706"
        />
        <SummaryCard
          label="Total Pemasukan"
          value={formatRupiah(totalPemasukan)}
          sub="bulan ini"
          icon={<TrendingUp size={15} />}
          onClick={() => onNavigate("pemasukan")}
          accent="#16A34A"
        />
        <SummaryCard
          label="Total Pengeluaran"
          value={formatRupiah(totalPengeluaran)}
          sub="bulan ini"
          icon={<TrendingDown size={15} />}
          onClick={() => onNavigate("pengeluaran")}
          accent="#DC2626"
        />
      </div>

      {/* Row 2 */}
      <div className="grid grid-cols-3 gap-3.5">
        {/* Invoice status */}
        <div className="bg-white rounded-lg border border-[#E2E6EC] p-4">
          <div className="flex items-center justify-between mb-3.5">
            <h3 className="text-[13px] font-semibold text-[#172033]">Status Invoice</h3>
            <button onClick={() => onNavigate("invoice")} className="text-[11px] text-[#315DA8] hover:underline flex items-center gap-0.5">
              Lihat Semua <ArrowRight size={10} />
            </button>
          </div>
          <div className="space-y-2.5">
            <StatusRow label="Belum Dibayar" count={statusCounts.belum_dibayar} color="#94A3B8" icon={<MinusCircle size={13} />} />
            <StatusRow label="Dibayar Sebagian" count={statusCounts.dibayar_sebagian} color="#D97706" icon={<Clock size={13} />} />
            <StatusRow label="Lunas" count={statusCounts.lunas} color="#16A34A" icon={<CheckCircle size={13} />} />
            <StatusRow label="Jatuh Tempo" count={statusCounts.jatuh_tempo} color="#DC2626" icon={<AlertCircle size={13} />} />
          </div>
          <div className="mt-3.5 pt-3 border-t border-[#F3F4F6] flex items-center justify-between">
            <span className="text-[11px] text-[#9CA3AF]">Saldo bersih periode ini</span>
            <span className="text-[13px] font-semibold text-[#172033]">{formatRupiah(totalPemasukan - totalPengeluaran)}</span>
          </div>
        </div>

        {/* Chart */}
        <div className="col-span-2 bg-white rounded-lg border border-[#E2E6EC] p-4">
          <div className="flex items-center justify-between mb-3.5">
            <h3 className="text-[13px] font-semibold text-[#172033]">Pemasukan vs Pengeluaran</h3>
            <div className="flex items-center gap-4 text-[11px] text-[#9CA3AF]">
              <div className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-sm bg-[#173B6C]" /> Pemasukan</div>
              <div className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-sm bg-[#EF4444]" /> Pengeluaran</div>
            </div>
          </div>
          <ResponsiveContainer width="100%" height={176}>
            <BarChart data={chartData} barSize={14} barGap={3}>
              <CartesianGrid vertical={false} stroke="#F3F4F6" />
              <XAxis dataKey="name" tick={{ fontSize: 11, fill: "#B0BAC7" }} axisLine={false} tickLine={false} />
              <YAxis tickFormatter={formatRpShort} tick={{ fontSize: 10, fill: "#B0BAC7" }} axisLine={false} tickLine={false} width={58} />
              <Tooltip
                contentStyle={{ fontSize: 12, border: "1px solid #E2E6EC", borderRadius: 6, boxShadow: "0 1px 6px rgba(0,0,0,0.06)", padding: "6px 10px" }}
                cursor={{ fill: "#F5F7FA" }}
              />
              <Bar dataKey="pemasukan" fill="#173B6C" radius={[3, 3, 0, 0]} />
              <Bar dataKey="pengeluaran" fill="#EF4444" radius={[3, 3, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Recent Transactions */}
      <div className="bg-white rounded-lg border border-[#E2E6EC]">
        <div className="flex items-center justify-between px-5 py-3.5 border-b border-[#E2E6EC]">
          <h3 className="text-[13px] font-semibold text-[#172033]">Invoice Terbaru</h3>
          <button onClick={() => onNavigate("invoice")} className="text-[11px] text-[#315DA8] hover:underline flex items-center gap-0.5">
            Lihat Semua <ArrowRight size={10} />
          </button>
        </div>
        <table className="w-full">
          <thead>
            <tr className="border-b border-[#F3F4F6]">
              <th className="text-left px-5 py-2.5 text-[11px] font-medium text-[#9CA3AF] uppercase tracking-wide">Nomor Invoice</th>
              <th className="text-left px-4 py-2.5 text-[11px] font-medium text-[#9CA3AF] uppercase tracking-wide">Klien</th>
              <th className="text-left px-4 py-2.5 text-[11px] font-medium text-[#9CA3AF] uppercase tracking-wide">Jatuh Tempo</th>
              <th className="text-right px-4 py-2.5 text-[11px] font-medium text-[#9CA3AF] uppercase tracking-wide">Total</th>
              <th className="text-left px-4 py-2.5 text-[11px] font-medium text-[#9CA3AF] uppercase tracking-wide">Status</th>
            </tr>
          </thead>
          <tbody>
            {recentInvoices.map((inv) => (
              <tr key={inv.id} className="border-b border-[#F9FAFB] hover:bg-[#FAFBFC] cursor-pointer transition-colors" onClick={() => onNavigate("detail-invoice", inv.id)}>
                <td className="px-5 py-3 text-[13px] font-semibold text-[#173B6C]">{inv.nomorInvoice}</td>
                <td className="px-4 py-3 text-[13px] text-[#172033]">{inv.klienNama}</td>
                <td className="px-4 py-3 text-[13px] text-[#9CA3AF]">{formatDate(inv.tanggalJatuhTempo)}</td>
                <td className="px-4 py-3 text-[13px] text-[#172033] text-right font-medium tabular-nums">{formatRupiah(inv.total)}</td>
                <td className="px-4 py-3"><StatusPembayaranBadge status={inv.statusPembayaran} /></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function SummaryCard({ label, value, sub, icon, onClick, accent }: {
  label: string; value: string; sub: string; icon: React.ReactNode; onClick: () => void; accent: string;
}) {
  return (
    <button onClick={onClick} className="bg-white rounded-lg border border-[#E2E6EC] px-4 py-4 text-left hover:border-[#D0D8E4] transition-colors group">
      <div className="flex items-center justify-between mb-3">
        <span className="text-[11px] font-medium text-[#9CA3AF] uppercase tracking-wider">{label}</span>
        <div className="flex items-center justify-center" style={{ color: accent + "CC" }}>
          {icon}
        </div>
      </div>
      <div className="text-[20px] font-bold text-[#172033] leading-tight tabular-nums">{value}</div>
      <div className="text-[11px] text-[#B0BAC7] mt-1">{sub}</div>
    </button>
  );
}

function StatusRow({ label, count, color, icon }: { label: string; count: number; color: string; icon: React.ReactNode }) {
  return (
    <div className="flex items-center justify-between gap-3">
      <div className="flex items-center gap-1.5 min-w-0">
        <span style={{ color }} className="flex-shrink-0">{icon}</span>
        <span className="text-[13px] text-[#4B5563] truncate">{label}</span>
      </div>
      <div className="flex items-center gap-2.5 flex-shrink-0">
        <div className="w-20 h-1 bg-[#F3F4F6] rounded-full overflow-hidden">
          <div className="h-full rounded-full" style={{ width: `${Math.min((count / 5) * 100, 100)}%`, background: color, opacity: 0.8 }} />
        </div>
        <span className="text-[13px] font-semibold text-[#172033] w-4 text-right">{count}</span>
      </div>
    </div>
  );
}

// resources/js/views/dashboard/Dashboard.vue
<script setup>
import { computed, ref } from 'vue';
import { useRouter } from 'vue-router';
import { AlertCircle, ArrowRight, CheckCircle, Clock, FileText, MinusCircle, TrendingDown, TrendingUp } from 'lucide-vue-next';
import BaseBadge from '@/components/ui/BaseBadge.vue';
import BaseCard from '@/components/ui/BaseCard.vue';
import { formatCurrency, formatDate } from '@/utils/formatters';
import { useInvoiceStore } from '@/stores/invoice';
import { usePaymentStore } from '@/stores/payment';
import { useFinanceStore } from '@/stores/finance';

const router = useRouter();
const invoiceStore = useInvoiceStore();
const paymentStore = usePaymentStore();
const financeStore = useFinanceStore();
const period = ref('Bulan Ini');
const activeChart = ref(null);
const dashboardChart = computed(() => ['Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Agu'].map((label, index) => { const month=String(index+3).padStart(2,'0'); return { label, income: financeStore.allIncomes.filter((item)=>item.date.slice(5,7)===month).reduce((total,item)=>total+item.amount,0), expense: financeStore.expenses.filter((item)=>item.date.slice(5,7)===month).reduce((total,item)=>total+item.amount,0) }; }));
const chartMax = computed(() => Math.max(10000000, ...dashboardChart.value.flatMap((item) => [item.income, item.expense])));
const chartTicks = computed(() => [chartMax.value, chartMax.value * .75, chartMax.value * .5, chartMax.value * .25, 0]);
const metrics = computed(() => ({
    totalInvoice: invoiceStore.invoices.filter((invoice) => invoice.status !== 'cancelled').length,
    outstanding: invoiceStore.invoices.filter((invoice) => invoice.status === 'published').reduce((total, invoice) => total + paymentStore.paymentSummaryByInvoice(invoice).remaining, 0),
    income: financeStore.allIncomes.reduce((total, value) => total + value.amount, 0),
    expense: financeStore.expenses.reduce((total, value) => total + value.amount, 0),
}));
const summaryCards = computed(() => [
    { label: 'Total Invoice', value: String(metrics.value.totalInvoice), sub: 'invoice aktif', icon: FileText, accent: '#173B6C', route: 'invoice' },
    { label: 'Sisa Tagihan', value: formatCurrency(metrics.value.outstanding), sub: 'belum terlunasi', icon: AlertCircle, accent: '#D97706', route: 'billing' },
    { label: 'Total Pemasukan', value: formatCurrency(metrics.value.income), sub: 'bulan ini', icon: TrendingUp, accent: '#16A34A', route: 'pemasukan' },
    { label: 'Total Pengeluaran', value: formatCurrency(metrics.value.expense), sub: 'bulan ini', icon: TrendingDown, accent: '#DC2626', route: 'pengeluaran' },
]);
const statusRows = computed(() => [
    { key: 'belum_dibayar', label: 'Belum Dibayar', color: '#94A3B8', icon: MinusCircle },
    { key: 'dibayar_sebagian', label: 'Dibayar Sebagian', color: '#D97706', icon: Clock },
    { key: 'lunas', label: 'Lunas', color: '#16A34A', icon: CheckCircle },
    { key: 'jatuh_tempo', label: 'Jatuh Tempo', color: '#DC2626', icon: AlertCircle },
].map((item) => ({ ...item, count: invoiceStore.invoices.filter((invoice) => invoice.status !== 'cancelled' && paymentStore.paymentSummaryByInvoice(invoice).status === item.key).length })));
const recentInvoices = computed(() => invoiceStore.invoices.map((invoice) => ({ ...invoice, issuedAt: invoice.date, dueAt: invoice.dueDate, total: paymentStore.paymentSummaryByInvoice(invoice).total, paymentStatus: paymentStore.paymentSummaryByInvoice(invoice).status })).sort((left, right) => right.issuedAt.localeCompare(left.issuedAt)).slice(0, 5));
const paymentBadge = (status) => ({ belum_dibayar: ['Belum Dibayar', 'neutral'], dibayar_sebagian: ['Dibayar Sebagian', 'warning'], lunas: ['Lunas', 'success'], jatuh_tempo: ['Jatuh Tempo', 'danger'] }[status]);
const chartHeight = (value) => Math.round((value / chartMax.value) * 134);
const chartY = (value) => 142 - chartHeight(value);
const goTo = (name) => router.push({ name });
const viewInvoice = (id) => router.push({ name: 'invoice-detail', params: { id } });
</script>

<template>
    <div class="space-y-4 p-6">
        <header class="flex items-center justify-between pb-1">
            <div><h1 class="text-[18px] font-semibold leading-snug text-[#172033]">Dashboard</h1><p class="mt-0.5 text-[13px] text-[#9CA3AF]">Ringkasan keuangan dan aktivitas terkini</p></div>
            <div class="relative"><select v-model="period" aria-label="Pilih periode dashboard" class="h-8 appearance-none rounded-md border border-[#E2E6EC] bg-white py-0 pl-3 pr-8 text-[13px] text-[#667085] outline-none focus:border-[#173B6C]"><option>Bulan Ini</option><option>3 Bulan Terakhir</option><option>Tahun Ini</option></select><svg class="pointer-events-none absolute right-2 top-1/2 -translate-y-1/2 text-[#9CA3AF]" width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 9 6 6 6-6" /></svg></div>
        </header>

        <div class="grid grid-cols-4 gap-3.5">
            <button v-for="card in summaryCards" :key="card.label" class="group rounded-lg border border-[#E2E6EC] bg-white px-4 py-4 text-left transition-colors hover:border-[#D0D8E4]" @click="goTo(card.route)"><div class="mb-3 flex items-center justify-between"><span class="text-[11px] font-medium uppercase tracking-wider text-[#9CA3AF]">{{ card.label }}</span><component :is="card.icon" :size="15" :style="{ color: `${card.accent}CC` }" /></div><p class="tabular-nums text-[20px] font-bold leading-tight text-[#172033]">{{ card.value }}</p><p class="mt-1 text-[11px] text-[#B0BAC7]">{{ card.sub }}</p></button>
        </div>

        <div class="grid grid-cols-3 gap-3.5">
            <BaseCard><div class="mb-3.5 flex items-center justify-between"><h2 class="text-[13px] font-semibold text-[#172033]">Status Invoice</h2><button class="flex items-center gap-0.5 text-[11px] text-[#315DA8] hover:underline" @click="goTo('invoice')">Lihat Semua <ArrowRight :size="10" /></button></div><div class="space-y-2.5"><div v-for="status in statusRows" :key="status.key" class="flex items-center justify-between gap-3"><div class="flex min-w-0 items-center gap-1.5"><component :is="status.icon" :size="13" class="shrink-0" :style="{ color: status.color }" /><span class="truncate text-[13px] text-[#4B5563]">{{ status.label }}</span></div><div class="flex shrink-0 items-center gap-2.5"><span class="h-1 w-20 overflow-hidden rounded-full bg-[#F3F4F6]"><span class="block h-full rounded-full opacity-80" :style="{ width: `${Math.min((status.count / 5) * 100, 100)}%`, background: status.color }" /></span><span class="w-4 text-right text-[13px] font-semibold text-[#172033]">{{ status.count }}</span></div></div></div><div class="mt-3.5 flex items-center justify-between border-t border-[#F3F4F6] pt-3"><span class="text-[11px] text-[#9CA3AF]">Saldo bersih periode ini</span><span class="text-[13px] font-semibold text-[#172033]">{{ formatCurrency(metrics.income - metrics.expense) }}</span></div></BaseCard>

            <BaseCard class="col-span-2"><div class="mb-3.5 flex items-center justify-between"><h2 class="text-[13px] font-semibold text-[#172033]">Pemasukan vs Pengeluaran</h2><div class="flex items-center gap-4 text-[11px] text-[#9CA3AF]"><span class="flex items-center gap-1.5"><i class="h-2.5 w-2.5 rounded-sm bg-[#173B6C]" />Pemasukan</span><span class="flex items-center gap-1.5"><i class="h-2.5 w-2.5 rounded-sm bg-[#EF4444]" />Pengeluaran</span></div></div><div class="relative h-44 w-full"><svg class="h-full w-full" viewBox="0 0 640 176" preserveAspectRatio="none" role="img" aria-label="Grafik pemasukan dan pengeluaran dari Maret hingga Agustus"><g v-for="tick in chartTicks" :key="tick"><line x1="60" x2="638" :y1="chartY(tick)" :y2="chartY(tick)" stroke="#F3F4F6" /><text x="0" :y="chartY(tick) + 3" fill="#B0BAC7" font-size="10">{{ tick === 0 ? 'Rp 0' : `Rp ${(tick / 1000000).toFixed(1)}jt` }}</text></g><g v-for="(month, index) in dashboardChart" :key="month.label" @mouseenter="activeChart = { ...month, index }" @mouseleave="activeChart = null"><rect :x="70 + index * 91" y="0" width="50" height="154" fill="transparent" /><rect :x="82 + index * 91" :y="chartY(month.income)" width="14" :height="chartHeight(month.income)" rx="3" ry="3" fill="#173B6C" /><rect :x="99 + index * 91" :y="chartY(month.expense)" width="14" :height="chartHeight(month.expense)" rx="3" ry="3" fill="#EF4444" /><text :x="98 + index * 91" y="171" text-anchor="middle" fill="#B0BAC7" font-size="11">{{ month.label }}</text></g></svg><div v-if="activeChart" class="pointer-events-none absolute z-10 rounded-[6px] border border-[#E2E6EC] bg-white px-2.5 py-1.5 text-xs shadow-sm" :style="{ left: `${Math.min(78, 11 + activeChart.index * 15)}%`, top: '8px' }"><p class="font-medium text-[#172033]">{{ activeChart.label }}</p><p class="text-[#173B6C]">Pemasukan: {{ formatCurrency(activeChart.income) }}</p><p class="text-[#EF4444]">Pengeluaran: {{ formatCurrency(activeChart.expense) }}</p></div></div></BaseCard>
        </div>

        <section class="overflow-x-auto rounded-lg border border-[#E2E6EC] bg-white"><div class="flex items-center justify-between border-b border-[#E2E6EC] px-5 py-3.5"><h2 class="text-[13px] font-semibold text-[#172033]">Invoice Terbaru</h2><button class="flex items-center gap-0.5 text-[11px] text-[#315DA8] hover:underline" @click="goTo('invoice')">Lihat Semua <ArrowRight :size="10" /></button></div><table class="w-full min-w-[640px]"><thead><tr class="border-b border-[#F3F4F6]"><th class="px-5 py-2.5 text-left text-[11px] font-medium uppercase tracking-wide text-[#9CA3AF]">Nomor Invoice</th><th class="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wide text-[#9CA3AF]">Klien</th><th class="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wide text-[#9CA3AF]">Jatuh Tempo</th><th class="px-4 py-2.5 text-right text-[11px] font-medium uppercase tracking-wide text-[#9CA3AF]">Total</th><th class="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wide text-[#9CA3AF]">Status</th></tr></thead><tbody><tr v-for="invoice in recentInvoices" :key="invoice.id" class="cursor-pointer border-b border-[#F9FAFB] transition-colors hover:bg-[#FAFBFC]" @click="viewInvoice(invoice.id)"><td class="px-5 py-3 text-[13px] font-semibold text-[#173B6C]">{{ invoice.number }}</td><td class="px-4 py-3 text-[13px] text-[#172033]">{{ invoice.client }}</td><td class="px-4 py-3 text-[13px] text-[#9CA3AF]">{{ formatDate(invoice.dueAt) }}</td><td class="px-4 py-3 text-right text-[13px] font-medium tabular-nums text-[#172033]">{{ formatCurrency(invoice.total) }}</td><td class="px-4 py-3"><BaseBadge :variant="paymentBadge(invoice.paymentStatus)[1]">{{ paymentBadge(invoice.paymentStatus)[0] }}</BaseBadge></td></tr></tbody></table></section>
    </div>
</template>
